# Generated by Django 4.2.6 on 2023-10-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_titulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='titulo',
        ),
    ]
