# Generated by Django 4.2.6 on 2023-10-18 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='tipoatuacao',
            options={'verbose_name_plural': 'Tipos de atuação'},
        ),
        migrations.CreateModel(
            name='produtora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pais')),
            ],
        ),
    ]
