# Generated by Django 4.2.6 on 2023-10-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_filme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='filme',
        ),
    ]
